language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'

jobs:
  include:
    - stage: test
      script:
        yarn run ci
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
