language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
script:
  - yarn run ci
after_success:
   - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
